export const API_FAILURE = 'API_FAILURE';


// Authentication.
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const AUTH_CURRENT_USER = 'AUTH_CURRENT_USER'; 
export const SIGNOUT_CURRENT_USER = 'SIGNOUT_CURRENT_USER';
export const CLEAR_CURRENT_USER_FAIL = 'CLEAR_CURRENT_USER_FAIL';


// Users.
export const INDEX_USERS_SUCCESS = 'INDEX_USERS_SUCCESS';


// Friends.
export const INDEX_FRIENDS_SUCCESS = 'INDEX_FRIENDS_SUCCESS';
export const INDEX_FRIENDS_FAILURE = 'INDEX_FRIENDS_FAILURE';
export const ADD_FRIEND_SUCCESS = 'ADD_FRIEND_SUCCESS';
export const ADD_FRIEND_FAILURE = 'ADD_FRIEND_FAILURE';


// Servers.
export const INDEX_USER_SERVERS_SUCCESS = 'INDEX_USER_SERVERS_SUCCESS';
export const INDEX_USER_SERVERS_FAILURE = 'INDEX_USER_SERVERS_FAILURE';
                                                                      ;
export const CREATE_USER_SERVER_SUCCESS = 'CREATE_USER_SERVER_SUCCESS';
export const CREATE_USER_SERVER_FAILURE = 'CREATE_USER_SERVER_FAILURE';
                                                                      ;
export const DELETE_USER_SERVER_SUCCESS = 'DELETE_USER_SERVER_SUCCESS';
export const DELETE_USER_SERVER_FAILURE = 'DELETE_USER_SERVER_FAILURE';
                                                                      ;
export const UPDATE_USER_SERVER_SUCCESS = 'UPDATE_USER_SERVER_SUCCESS';
export const UPDATE_USER_SERVER_FAILURE = 'UPDATE_USER_SERVER_FAILURE';


// Channels.
export const INDEX_SERVER_CHANNELS_SUCCESS = 'INDEX_SERVER_CHANNELS_SUCCESS';
export const INDEX_SERVER_CHANNELS_FAILURE = 'INDEX_SERVER_CHANNELS_FAILURE';
export const CREATE_SERVER_CHANNEL_SUCCESS = 'CREATE_SERVER_CHANNEL_SUCCESS';
export const CREATE_SERVER_CHANNEL_FAILURE = 'CREATE_SERVER_CHANNEL_FAILURE';
export const DELETE_SERVER_CHANNEL_SUCCESS = 'DELETE_SERVER_CHANNEL_SUCCESS';
export const DELETE_SERVER_CHANNEL_FAILURE = 'DELETE_SERVER_CHANNEL_FAILURE';
export const UPDATE_SERVER_CHANNEL_SUCCESS = 'UPDATE_SERVER_CHANNEL_SUCCESS';
export const UPDATE_SERVER_CHANNEL_FAILURE = 'UPDATE_SERVER_CHANNEL_FAILURE';


// Messages.
export const INDEX_CHANNEL_MESSAGES_SUCCESS = 'INDEX_CHANNEL_MESSAGES_SUCCESS';
export const INDEX_CHANNEL_MESSAGES_FAILURE = 'INDEX_CHANNEL_MESSAGES_FAILURE';
export const CREATE_CHANNEL_MESSAGE_SUCCESS = 'CREATE_CHANNEL_MESSAGE_SUCCESS';
export const CREATE_CHANNEL_MESSAGE_FAILURE = 'CREATE_CHANNEL_MESSAGE_FAILURE';


// Socket
export const CHANGE_ROOM = 'CHANGE_ROOM';
export const SEND_MESSAGE = 'SEND_MESSAGE';


