// Authentication.
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const AUTH_CURRENT_USER = 'AUTH_CURRENT_USER'; 
export const SIGNOUT_CURRENT_USER = 'SIGNOUT_CURRENT_USER';
export const CLEAR_CURRENT_USER_FAIL = 'CLEAR_CURRENT_USER_FAIL';

// Servers.
export const INDEX_USER_SERVERS_SUCCESS = 'INDEX_USER_SERVERS_SUCCESS';
export const INDEX_USER_SERVERS_FAILURE = 'INDEX_USER_SERVERS_FAILURE';
                                                                      ;
export const CREATE_USER_SERVER_SUCCESS = 'CREATE_USER_SERVER_SUCCESS';
export const CREATE_USER_SERVER_FAILURE = 'CREATE_USER_SERVER_FAILURE';
                                                                      ;
export const DELETE_USER_SERVER_SUCCESS = 'DELETE_USER_SERVER_SUCCESS';
export const DELETE_USER_SERVER_FAILURE = 'DELETE_USER_SERVER_FAILURE';
                                                                      ;
export const UPDATE_USER_SERVER_SUCCESS = 'UPDATE_USER_SERVER_SUCCESS';
export const UPDATE_USER_SERVER_FAILURE = 'UPDATE_USER_SERVER_FAILURE';

// Channels.
export const INDEX_USER_CHANNELS_SUCCESS = 'INDEX_USER_CHANNELS_SUCCESS';
export const INDEX_USER_CHANNELS_FAILURE = 'INDEX_USER_CHANNELS_FAILURE';
	
export const INDEX_SERVER_CHANNELS_SUCCESS = 'INDEX_SERVER_CHANNELS_SUCCESS';
export const INDEX_SERVER_CHANNELS_FAILURE = 'INDEX_SERVER_CHANNELS_FAILURE';
export const CREATE_SERVER_CHANNEL_SUCCESS = 'CREATE_SERVER_CHANNEL_SUCCESS';
export const CREATE_SERVER_CHANNEL_FAILURE = 'CREATE_SERVER_CHANNEL_FAILURE';
export const DELETE_SERVER_CHANNEL_SUCCESS = 'DELETE_SERVER_CHANNEL_SUCCESS';
export const DELETE_SERVER_CHANNEL_FAILURE = 'DELETE_SERVER_CHANNEL_FAILURE';
export const UPDATE_SERVER_CHANNEL_SUCCESS = 'UPDATE_SERVER_CHANNEL_SUCCESS';
export const UPDATE_SERVER_CHANNEL_FAILURE = 'UPDATE_SERVER_CHANNEL_FAILURE';
