// Authentication.
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const AUTH_CURRENT_USER = 'AUTH_CURRENT_USER'; 
export const SIGNOUT_CURRENT_USER = 'SIGNOUT_CURRENT_USER';
export const CLEAR_CURRENT_USER_FAIL = 'CLEAR_CURRENT_USER_FAIL';

// Servers.
export const INDEX_USER_SERVERS_SUCCESS = 'INDEX_USER_SERVERS_SUCCESS'
export const INDEX_USER_SERVERS_FAILURE = 'INDEX_USER_SERVERS_FAILURE'

export const CREATE_USER_SERVER_SUCCESS = 'CREATE_USER_SERVER_SUCCESS'
export const CREATE_USER_SERVER_FAILURE = 'CREATE_USER_SERVER_FAILURE'

export const DELETE_USER_SERVER_SUCCESS = 'DELETE_USER_SERVER_SUCCESS'
export const DELETE_USER_SERVER_FAILURE = 'DELETE_USER_SERVER_FAILURE'

export const UPDATE_USER_SERVER_SUCCESS = 'UPDATE_USER_SERVER_SUCCESS'
export const UPDATE_USER_SERVER_FAILURE = 'UPDATE_USER_SERVER_FAILURE'


